buttons = {	'one': 'undo', 
			'two': 'metronome', 
			'three': 'escape', 
			'four': 'up', 
			'five': 'focus_browser', 
			'six': 'rotate', 
			'seven': 'step_rec', 
			'eight': 'save', 
			'nine': 'quantize', 
			'ten': 'rand_pat', 
			'eleven': 'arm_track', 
			'twelve': 'nothing', 
			'thirteen': 'mute', 
			'fourteen': 'cut', 
			'fifteen': 'copy', 
			'sixteen': 'paste', 

			'seventeen': 'solo', 
			'eighteen': 'enter', 
			'nineteen': 'left', 
			'twenty': 'down', 
			'twentyone': 'right', 
			'twentytwo': 'toggle_range', 
			'twentythree': 'open_channel', 
			'twentyfour': 'step_param', 
			'twentyfive': 'change_color', 
			'twentysix': 'rand_notes', 
			'twentyseven': 'nothing', 
			'twentyeight': 'nothing', 
			'twentynine': 'nothing', 
			'thirty': 'nothing', 
			'thirtyone': 'delete', 
			'thirtytwo': 'copy_all', 
			
			'thirtythree': 'song_pat', 
			'thirtyfour': 'overdub', 
			'thirtyfive': 'focus_playlist', 
			'thirtysix': 'focus_piano', 
			'thirtyseven': 'focus_channels', 
			'thirtyeight': 'focus_mixer', 
			'thirtynine': 'open_plugins', 
			'forty': 'pad_mode', 
			'fortyone': 'link_mix', 
			'fortytwo': 'shift', 
			'fortythree': 'alt', 
			'fortyfour': 'nothing', 
			'fortyfive': 'nothing', 
			'fortysix': 'wait_for_input', 
			'fortyseven': 'item_menu', 
			'fortyeight': 'tap_tempo', 

			'left': 'prev_pre_pat', 
			'right': 'next_pre_pat', 'loop': 'loop_record'}


